model:
  name: distilroberta-base
  tokenizer: distilroberta-base

processing:
  batch_size: 32
  max_length: 128

training:
  max_epochs: 3
  save_total_limit: 3
  learning_rate: 5e-5
  load_best_model_at_end: True
  fp16: True
  per_device_train_batch_size: 32
  per_device_eval_batch_size: ${training.per_device_train_batch_size}
  run_name: intent-detection-distil-roberta-v1